### ISSUE TITLE
What is the running environment of this code

### ISSUE THREAD

**Issue by guanfang12** [shiyujiao/IBL#1]
What is the running environment of this code?
What is the version of the python(3.6?)
What is the version of the tensorflow(1.4?)

**Comment by YujiaoShi** [comment]
Should be python3.6, tensorflow 1.15

**Comment by guanfang12** [comment]
Sorry to keep interrupting, when I test the "polar_transformer" script, I get the error as:
Traceback (most recent call last):
  File "polar_transformer.py", line 160, in <module>
    images = sess.run(image)
  File "/home/**/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/**/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/**/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/**/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[206279] = [0, 99, -1, 2] does not index into param shape [2,256,256,3]
         [[node GatherNd_3 (defined at /home/wxl/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Do you have the solution for this?

Ps: 
The code # from utils import tf_shape
can't work, so I add the following function at the beginning of "polar_transformer.py".
def tf_shape(x, rank):
    static_shape = x.get_shape().with_rank(rank).as_list()
    dynamic_shape = tf.unstack(tf.shape(x), rank)
    return [s if s is not None else d for s,d in zip(static_shape, dynamic_shape)]
